/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autobuyerdesign;

/**
 *
 * @author Yannick
 */
public class Nations {

    static Nations instance;

    public static Nations getInstance() {
        if (instance == null) {
            instance = new Nations();
        }
        return instance;
    }

    String[] nations = {"Argentinia",
        "Brasilien",
        "England",
        "Frankreich",
        "Deutschland",
        "Niederlande",
        "Italien",
        "Portugal",
        "Spanien",
        "Ä Guinea",
        "Afghanistan",
        "Ägypten",
        "Albanien",
        "Algerien",
        "Angola",
        "Antig & B",
        "Armenien",
        "Aserbaid",
        "Äthiopien",
        "Australien",
        "Barbados",
        "Belgien",
        "Belize",
        "Benin",
        "Bermuda",
        "Bolivien",
        "Bosnien H",
        "Brunei D",
        "Bulgarien",
        "Burk Faso",
        "Burundi",
        "Chile",
        "China VR",
        "Costa Rica",
        "CTA",
        "Dänemark",
        "Dom Rep",
        "DR Kongo",
        "Ecuador",
        "El Salvad",
        "Elfenbeinküste",
        "Eritrea",
        "Estland",
        "Färöer",
        "Fidschi",
        "Finnland",
        "Gabun",
        "Gambia",
        "Georgien",
        "Ghana",
        "Gibraltar",
        "Greneda",
        "Griechenland",
        "Guam",
        "Guatamale",
        "Guinea",
        "Guinea B",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hongkong",
        "Irak",
        "Irland",
        "Island",
        "Israel",
        "Jamaika",
        "Japan",
        "Kamerun",
        "Kanada",
        "Kap Verde",
        "Kasachstan",
        "Katar",
        "Kenia",
        "Kirgisistan",
        "Kolumbien",
        "Komoren",
        "Kongo",
        "Korea DVR",
        "Korea Rep",
        "Kosovo",
        "Kroatien",
        "Kuba",
        "Kuwait",
        "Lettland",
        "Libanon",
        "Liberia",
        "Libyen",
        "Liechtenstein",
        "Litauen",
        "Luxemburg",
        "Madagaskar",
        "Mali",
        "Malta",
        "Marokko",
        "Mauretanien",
        "Mauritius",
        "Mazedonien",
        "Mexiko",
        "Moldawien",
        "Montenegro",
        "Montserrat",
        "Mosambik",
        "N. Antillen",
        "Namibia",
        "Neukaled",
        "Neuseeland",
        "Niederlande",
        "Niger",
        "Nigeria",
        "Nordirland",
        "Norwegen",
        "Oman",
        "Österreich",
        "Palästina",
        "Panama",
        "Paraguay",
        "Peru",
        "Philippinen",
        "Polen",
        "Puerto Rico",
        "Rumänien",
        "Russland",
        "S.-Afrika",
        "Sambia",
        "San Marino",
        "Saudi-.A",
        "Schottland",
        "Schweden",
        "Schweiz",
        "Senegal",
        "Serbien",
        "Sierra L.",
        "Simbabwe",
        "Slowakei",
        "Slowenien",
        "Somalia",
        "Sri Lanka",
        "St. Kittis",
        "St. Lucia",
        "Sudan",
        "Suriname",
        "Syrien",
        "Tansania",
        "Thailand",
        "Togo",
        "Trinidad",
        "Tschad",
        "Tschechien",
        "Tunesien",
        "Türkei",
        "Turkmenistan",
        "Uganda",
        "Ukraine",
        "Ungarn",
        "Uruguay",
        "USA",
        "Usbekistan",
        "Venezuela",
        "Vietnam",
        "Wales",
        "Weissrussland",
        "Zypern"};

}
